# Generated by Django 5.0.6 on 2024-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredients_in_coctail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_coctail', models.IntegerField()),
                ('id_ingredient', models.IntegerField()),
                ('Amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='picture',
        ),
    ]
